services:
  - type: web
    name: dashmile-logistics
    env: node
    plan: free
    buildCommand: npm install && npm run build:frontend && npx prisma generate --schema=backend/prisma/schema.prisma && npx prisma db push --accept-data-loss --schema=backend/prisma/schema.prisma && npm run prisma:seed --workspace=backend && npm run build:backend
    startCommand: npm start
    envVars:
      - key: PORT
        value: 5000
      - key: JWT_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production
